displayName=Real Loot Key Value
author=elie
description=Shows the real Grand Exchange value of PvP loot keys in the loot chest interface (And doesnt round to the nearest million). 
tags=loot,key,value,pvp,wilderness
plugins=com.reallootkeyvalue.RealLootKeyValuePlugin
build=standard
